name: CMake on Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --clean-first

      - name: Test
        working-directory: ${{github.workspace}}\build\test
        run: .\Debug\all_tests.exe

      - name: Main
        working-directory: ${{github.workspace}}
        run: Get-Content .\input\mock_input.txt | & .\build\Debug\main.exe
